### ISSUE TITLE
suite model potentially wrong

### ISSUE THREAD

**Issue by atrifan** [adobe/athena#12]
Tests should not present a dependency to a suite.

Suite model is potentially wrong. A suite should look like:

```
.....
scenario:
given: >
....
then: >
....
when: >
....
tests:
   - ref: "name"
      version: "x.x"
      pottential overriding fields (must respect test model)
```

Please change the entity parsing logic to refer tests inside suites not the other way around

**Comment by catalin-me** [comment]
Fixed in #31
